#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import subprocess
import sys
from typing import List, Optional, Dict, Any, Tuple
from pathlib import Path
import shutil
import pwd
import grp
from datetime import datetime
import json
import glob
import traceback
from collections import defaultdict

sys.path.append(Path(__file__).parent / "utilities")
import utilities.metadata.gather_metadata as metadata_util
import utilities.cli.util as holohub_cli_util
from utilities.cli.container import HoloHubContainer
# from utilities.cli.project import ProjectMetadata, ProjectType

host_root_dir = Path(__file__).parent

def list_cmake_dir_options(script_dir: Path, cmake_function: str) -> List[str]:
    """Get list of directories from CMakeLists.txt files"""
    results = []
    for cmakelists in script_dir.rglob('CMakeLists.txt'):
        with open(cmakelists) as f:
            content = f.read()
            for line in content.splitlines():
                if cmake_function in line:
                    try:
                        name = line.split('(')[1].split(')')[0].strip()
                        results.append(name)
                    except IndexError:
                        continue
    return sorted(results)



class HoloHubCLI:
    """Command-line interface for HoloHub"""
    
    def __init__(self):
        self.parser = self._create_parser()
        
        # Add build configuration
        self.build_dir = host_root_dir / "build"
        self.data_dir = os.environ.get('HOLOHUB_DATA_PATH', 
                                     host_root_dir / "data")
        self.holoscan_sdk_install = os.environ.get('HOLOSCAN_LIB_PATH',
                                                  '/opt/nvidia/holoscan/lib')
        self._collect_metadata()

    def _create_parser(self) -> argparse.ArgumentParser:
        """Create the argument parser with all supported commands"""
        parser = argparse.ArgumentParser(
            description='HoloHub CLI tool for managing HoloHub applications and containers'
        )
        subparsers = parser.add_subparsers(dest='command', required=True)
        
        # build-container command
        build_container = subparsers.add_parser('build-container', 
            help='Build the development container')
        build_container.add_argument('project', nargs='?',
            help='Project to build container for')
        build_container.add_argument('--base_img',
            help='Fully qualified base image name')
        build_container.add_argument('--docker_file',
            help='Path to Dockerfile to use')
        build_container.add_argument('--img',
            help='Specify fully qualified container name')
        build_container.add_argument('--verbose', action='store_true',
            help='Print variables passed to docker build command')
        build_container.add_argument('--no-cache', action='store_true',
            help='Do not use cache when building the image')
        build_container.add_argument('--build-args',
            help='Provides extra arguments to docker build command')
        build_container.add_argument('--dryrun', action='store_true',
            help='Print commands without executing them')
        build_container.set_defaults(func=self.handle_build_container)

        # run-container command
        run_container = subparsers.add_parser('run-container',
            help='Launch the development container')
        run_container.add_argument('--img',
            help='Fully qualified image name')
        run_container.add_argument('--local_sdk_root',
            help='Path to Holoscan SDK used for building local Holoscan SDK container')
        run_container.add_argument('--ssh_x11', action='store_true',
            help='Enable X11 forwarding of graphical HoloHub applications over SSH')
        run_container.add_argument('--init', action='store_true',
            help='Support tini entry point')
        run_container.add_argument('--persistent', action='store_true',
            help='Does not delete container after it is run')
        run_container.add_argument('--verbose', action='store_true',
            help='Print variables passed to docker run command')
        run_container.add_argument('--dryrun', action='store_true',
            help='Print commands without executing them')
        run_container.add_argument('--add-volume', action='append',
            help='Mount additional volume')
        run_container.add_argument('--as_root', action='store_true',
            help='Run the container with root permissions')
        run_container.add_argument('--docker_opts',
            help='Additional options to pass to the Docker launch')
        run_container.set_defaults(func=self.handle_run_container)

        # build command
        build = subparsers.add_parser('build',
            help='Build a project')
        build.add_argument('project',
            help='Project to build')
        build.add_argument('--local', action='store_true',
            help='Build locally instead of in container')
        build.add_argument('--verbose', action='store_true',
            help='Print extra output')
        build.add_argument('--build-type', choices=['debug', 'release', 'rel-debug'],
            help='Build type (debug, release, rel-debug)')
        build.add_argument('--dryrun', action='store_true',
            help='Print commands without executing them')
        build.set_defaults(func=self.handle_build)

        # run command
        run = subparsers.add_parser('run',
            help='Run a project')
        run.add_argument('project',
            help='Project to run')
        run.add_argument('--local', action='store_true',
            help='Run locally instead of in container')
        run.add_argument('--verbose', action='store_true',
            help='Print extra output')
        run.add_argument('--dryrun', action='store_true',
            help='Print commands without executing them')
        run.add_argument('--nsys-profile', action='store_true',
            help='Enable Nsight Systems profiling')
        run.add_argument('--language', choices=['cpp', 'python'],
            help='Specify language implementation')
        run.set_defaults(func=self.handle_run)

        # list command
        list_cmd = subparsers.add_parser('list',
            help='List all available targets')
        list_cmd.set_defaults(func=self.handle_list)
        
        # lint command
        lint = subparsers.add_parser('lint',
            help='Run linting tools')
        lint.add_argument('path', nargs='?', default='.',
            help='Path to lint')
        lint.add_argument('--fix', action='store_true',
            help='Fix linting issues')
        lint.add_argument('--install-dependencies', action='store_true',
            help='Install linting dependencies')
        lint.add_argument('--dryrun', action='store_true',
            help='Print commands without executing them')
        lint.set_defaults(func=self.handle_lint)
        
        # setup command
        setup = subparsers.add_parser('setup',
            help='Install HoloHub main required packages')
        setup.add_argument('--dryrun', action='store_true',
            help='Print commands without executing them')
        setup.set_defaults(func=self.handle_setup)

        # Add install command
        install = subparsers.add_parser('install',
            help='Install a project')
        install.add_argument('project',
            help='Project to install')
        install.add_argument('--local', action='store_true',
            help='Install locally instead of in container')
        install.add_argument('--build-type', choices=['debug', 'release', 'rel-debug'],
            help='Build type (debug, release, rel-debug)')
        install.add_argument('--dryrun', action='store_true',
            help='Print commands without executing them')
        install.set_defaults(func=self.handle_install)

        # Add clear-cache command
        clear_cache = subparsers.add_parser('clear-cache',
            help='Clear cache folders')
        clear_cache.add_argument('--dryrun', action='store_true',
            help='Print commands without executing them')
        clear_cache.set_defaults(func=self.handle_clear_cache)

        return parser

    def _collect_metadata(self) -> None:
        """Create an unstructured database of metadata for all projects"""

        EXCLUDE_PATHS = ["applications/holoviz/template"]
        # Known exceptions, such as template files that do not represent a standalone project

        app_paths = (
            host_root_dir / "applications",
            host_root_dir / "benchmarks",
            host_root_dir / "gxf_extensions",
            host_root_dir / "operators",
            host_root_dir / "pkg",
            host_root_dir / "workflows"
        )
        self.projects = metadata_util.gather_metadata(app_paths, exclude_paths=EXCLUDE_PATHS)

    def _find_project(self, project_name: str, language: Optional[str] = None) -> dict:
        """Find a project by name"""
        normalized_language = holohub_cli_util.normalize_language(language) if language else None
        for project in self.projects:
            if project['application_name'] == project_name:
                if normalized_language and holohub_cli_util.normalize_language(project['metadata']['language']) != normalized_language:
                    continue
                return project
        return None

    def handle_build_container(self, args: argparse.Namespace) -> None:
        """Handle build-container command"""
        self.container.do_dry_run = args.dryrun
        self.container.build(
            docker_file=args.docker_file,
            base_img=args.base_img,
            img=args.img,
            no_cache=args.no_cache,
            build_args=args.build_args,
            project=args.project,
            verbose=args.verbose
        )

    def handle_run_container(self, args: argparse.Namespace) -> None:
        """Handle run-container command"""
        self.container.do_dry_run = args.dryrun
        self.container.launch(
            img=args.img,
            local_sdk_root=args.local_sdk_root or "undefined",
            ssh_x11=args.ssh_x11,
            use_tini=args.init,
            persistent=args.persistent,
            as_root=args.as_root,
            docker_opts=args.docker_opts or "",
            add_volumes=args.add_volume,
            verbose=args.verbose
        )

    def get_buildtype_str(self, build_type: Optional[str]) -> str:
        """Get CMake build type string"""
        if not build_type:
            return os.environ.get('CMAKE_BUILD_TYPE', 'Release')
            
        build_type_map = {
            'debug': 'Debug',
            'Debug': 'Debug',
            'release': 'Release',
            'Release': 'Release',
            'rel-debug': 'RelWithDebInfo',
            'RelWithDebInfo': 'RelWithDebInfo'
        }
        return build_type_map.get(build_type, 'Release')

    # def get_app_default_language(self, app_name: str) -> str:
    #     """Get default language if multiple are available"""
    #     DEFAULT_LANGUAGE = 'cpp'
    #     apps = holohub_cli_util.list_metadata_json_dir(
    #         host_root_dir / "applications",
    #         host_root_dir / "benchmarks",
    #         host_root_dir / "workflows"
    #     )
    #     for name, lang in apps:
    #         if name == app_name:
    #             return lang.strip('()') if lang else DEFAULT_LANGUAGE
    #     return DEFAULT_LANGUAGE

    def handle_build(self, args: argparse.Namespace) -> None:
        """Handle build command"""
        project_data = self._find_project(
            project_name=args.project,
            language=args.language if hasattr(args, 'language') else None
        )
        if not project_data:
            holohub_cli_util.fatal(f"Project '{args.project}' {f'({args.language})' if hasattr(args, 'language') else ''} not found")

        if args.local:
            app_source = get_app_source_root_dir(args.project, host_root_dir)
            
            if not language:
                holohub_cli_util.fatal("Could not determine project language. Please specify with --language")
                
            app_source = get_app_source_lang_dir(args.project, language, host_root_dir)
            build_type = self.get_buildtype_str(args.build_type)
            
            # Local build
            build_dir = self.build_dir / args.project
            build_dir.mkdir(parents=True, exist_ok=True)
            
            if language == 'cpp':
                # Build C++ project
                holohub_cli_util.run_command([
                    'cmake', '-B', str(build_dir),
                    '-S', str(app_source),
                    f'-DCMAKE_BUILD_TYPE={build_type}',
                    f'-DCMAKE_PREFIX_PATH={self.holoscan_sdk_install}'
                ], dry_run=args.dryrun)
                holohub_cli_util.run_command(['cmake', '--build', str(build_dir), '--config', build_type],
                          dry_run=args.dryrun)
            else:
                # For Python projects, just create the directory
                pass
        else:
            # Build in container 
            container = HoloHubContainer(project_metadata=project_data)
            container.dryrun = args.dryrun
            container.build()
            # self.container.launch(
            #     docker_opts="--entrypoint=bash",
            #     extra_args=['-c', f'holohub build {args.project} --language {language} --local'],
            #     verbose=args.verbose
            # )

    def handle_run(self, args: argparse.Namespace) -> None:
        """Handle run command"""
        if args.local:
            app_source = get_app_source_root_dir(args.project, host_root_dir)
            language = args.language or self.get_app_default_language(args.project)
            
            if not language:
                holohub_cli_util.fatal("Could not determine project language. Please specify with --language")
                
            app_source = get_app_source_lang_dir(args.project, language, host_root_dir)
            metadata = get_metadata(app_source)
            
            # Get run configuration from metadata
            project_type = "benchmark" if "benchmark" in metadata else "application"
            run_config = metadata[project_type]["run"]
            
            # Process command template
            cmd = run_config["command"]
            cmd = cmd.replace("<holohub_data_dir>", str(self.data_dir))
            cmd = cmd.replace("<holohub_app_source>", str(app_source))
            
            if language == 'cpp':
                build_dir = self.build_dir / args.project
                cmd = cmd.replace("<holohub_app_bin>", str(build_dir))
                
                if not build_dir.is_dir() and not args.dryrun:
                    holohub_cli_util.fatal(f"The build directory for this application does not exist.\n"
                          f"Did you forget to './holohub build {args.project}'?")
            
            # Handle workdir
            workdir = run_config.get("workdir", "holohub_app_bin")
            if workdir == "holohub_app_source":
                if not args.dryrun:
                    os.chdir(app_source)
                print(f"\033[34m{get_timestamp()} \033[37m$ \033[32mcd {app_source}\033[0m")
            elif workdir == "holohub_bin":
                if not args.dryrun:
                    os.chdir(self.build_dir)
                print(f"\033[34m{get_timestamp()} \033[37m$ \033[32mcd {self.build_dir}\033[0m")
            else:  # default to app binary directory
                target_dir = build_dir if language == 'cpp' else app_source
                if not args.dryrun:
                    os.chdir(target_dir)
                print(f"\033[34m{get_timestamp()} \033[37m$ \033[32mcd {target_dir}\033[0m")
            
            # Set up environment
            env = os.environ.copy()
            env['PYTHONPATH'] = f"{self.holoscan_sdk_install}/../python/lib:{self.build_dir}/python/lib:{host_root_dir}"
            env['HOLOHUB_DATA_PATH'] = str(self.data_dir)
            env['HOLOSCAN_INPUT_PATH'] = os.environ.get('HOLOSCAN_INPUT_PATH', str(self.data_dir))
            
            # Print environment setup
            if args.verbose or args.dryrun:
                print(f"\033[34m{get_timestamp()} \033[37m$ \033[32mexport PYTHONPATH={env['PYTHONPATH']}\033[0m")
                print(f"\033[34m{get_timestamp()} \033[37m$ \033[32mexport HOLOHUB_DATA_PATH={env['HOLOHUB_DATA_PATH']}\033[0m")
                print(f"\033[34m{get_timestamp()} \033[37m$ \033[32mexport HOLOSCAN_INPUT_PATH={env['HOLOSCAN_INPUT_PATH']}\033[0m")
            
            # Handle Nsight Systems profiling
            if args.nsys_profile:
                if not shutil.which('nsys') and not os.path.isdir('/opt/nvidia/nsys-host') and not args.dryrun:
                    holohub_cli_util.fatal("Nsight Systems CLI command 'nsys' not found. No Nsight installation from the host is also mounted.")
                nsys_cmd = '/opt/nvidia/nsys-host/bin/nsys' if not shutil.which('nsys') else 'nsys'
                
                # Check perf_event_paranoid level
                if not args.dryrun:
                    try:
                        with open('/proc/sys/kernel/perf_event_paranoid') as f:
                            if int(f.read()) > 2:
                                holohub_cli_util.fatal("For Nsight Systems profiling the Linux operating system's perf_event_paranoid level must be 2 or less.")
                    except (IOError, ValueError):
                        pass
                
                cmd = f"{nsys_cmd} profile --trace=cuda,vulkan,nvtx,osrt {cmd}"
            
            holohub_cli_util.run_command(cmd.split(), env=env, dry_run=args.dryrun)
        else:
            # Pass dryrun to container launch if specified
            self.container.do_dry_run = args.dryrun
            
            # Get language before launching container
            language = args.language or self.get_app_default_language(args.project)
            if not language:
                holohub_cli_util.fatal("Could not determine project language. Please specify with --language")
            
            # Build command with all necessary arguments
            run_cmd = f'holohub run {args.project} --language {language} --local'
            if args.dryrun:
                run_cmd += ' --dryrun'
            if args.verbose:
                run_cmd += ' --verbose'
            if args.nsys_profile:
                run_cmd += ' --nsys-profile'
                
            self.container.launch(
                docker_opts="--entrypoint=bash",
                extra_args=['-c', run_cmd],
                verbose=args.verbose
            )

    def handle_list(self, args: argparse.Namespace) -> None:
        """Handle list command"""
        LIST_TYPES = ["application", "benchmark", "gxf_extension", "package", "operator", "tutorial", "workflow"]
        EXCLUDE_PATHS = ["applications/holoviz/template"]
        # Known exceptions, such as template files that do not represent a standalone project

        app_paths = (
            host_root_dir / "applications",
            host_root_dir / "benchmarks",
            host_root_dir / "gxf_extensions",
            host_root_dir / "operators",
            host_root_dir / "pkg",
            host_root_dir / "workflows"
        )
        metadata = metadata_util.gather_metadata(app_paths, exclude_paths=EXCLUDE_PATHS)
        grouped_metadata = defaultdict(list)
        for project in metadata:
            grouped_metadata[project.get('project_type', '')].append(project)

        for project_type in LIST_TYPES:
            if project_type not in grouped_metadata:
                continue
            print(f"\n\033[1;37m== {project_type.upper()}S =================\033[0m\n")
            for project in grouped_metadata[project_type]:
                language = project.get('metadata', {}).get('language', '')
                language = f"({language})" if language else ""
                print(f'{project["application_name"]} {language}')
            
        print("\n\033[1;37m=================================\033[0m\n")

    def handle_lint(self, args: argparse.Namespace) -> None:
        """Handle lint command"""
        if args.install_dependencies:
            self._install_lint_deps()
            return
            
        exit_code = 0
        
        # Change to script directory
        os.chdir(host_root_dir)
        
        if args.fix:
            # Fix Python
            holohub_cli_util.run_command(['ruff', 'check', '--fix', '--ignore', 'E712', args.path], check=False)
            holohub_cli_util.run_command(['isort', args.path], check=False)
            holohub_cli_util.run_command(['black', args.path], check=False)
            holohub_cli_util.run_command(['codespell', '-w', '-i', '3', args.path,
                        '--ignore-words', 'codespell_ignore_words.txt',
                        '--skip=*.onnx,*.min.js,*.min.js.map,Contrastive_learning_Notebook.ipynb,./data'],
                       check=False)
            
            # Fix C++ with clang-format
            try:
                cpp_files = subprocess.check_output(
                    [sys.executable, '-m', 'cpplint',
                     '--exclude', 'build',
                     '--exclude', 'install',
                     '--exclude', 'build-*',
                     '--exclude', 'install-*',
                     '--exclude', 'applications/holoviz/template/cookiecutter*',
                     '--recursive', args.path],
                    stderr=subprocess.PIPE,
                    text=True
                )
                for file in cpp_files.splitlines():
                    if ':' in file:  # Only process files with issues
                        file = file.split(':')[0]
                        holohub_cli_util.run_command(['clang-format', '--style=file', '--sort-includes=0',
                                   '--lines=20:10000', '-i', file], check=False)
            except subprocess.CalledProcessError:
                pass
                
        else:
            # Run linting checks
            print("Linting Python")
            if holohub_cli_util.run_command(['ruff', 'check', '--ignore', 'E712', args.path], check=False).returncode != 0:
                exit_code = 1
            if holohub_cli_util.run_command(['isort', '-c', args.path], check=False).returncode != 0:
                exit_code = 1
            if holohub_cli_util.run_command(['black', '--check', args.path], check=False).returncode != 0:
                exit_code = 1
                
            print("Linting C++")
            if holohub_cli_util.run_command(['python', '-m', 'cpplint',
                          '--exclude', 'build',
                          '--exclude', 'install',
                          '--exclude', 'build-*',
                          '--exclude', 'install-*',
                          '--exclude', '.vscode-server',
                          '--exclude', 'applications/holoviz/template/cookiecutter*',
                          '--recursive', args.path], check=False).returncode != 0:
                exit_code = 1
                
            print("Code spelling")
            if holohub_cli_util.run_command(['codespell', args.path,
                          '--skip=*.onnx,*.min.js,*.min.js.map,Contrastive_learning_Notebook.ipynb,./data',
                          '--ignore-words', 'codespell_ignore_words.txt',
                          '--exclude-file', 'codespell.txt'], check=False).returncode != 0:
                exit_code = 1
                
            print("Linting CMake")
            cmake_files = list(Path(args.path).rglob('CMakeLists.txt'))
            cmake_files.extend(Path(args.path).rglob('*.cmake'))
            if cmake_files:
                if holohub_cli_util.run_command(['cmakelint',
                              '--filter=-whitespace/indent,-linelength,-readability/wonkycase,-convention/filename,-package/stdargs',
                              *[str(f) for f in cmake_files]], check=False).returncode != 0:
                    exit_code = 1
                    
        if exit_code == 0:
            print("Everything looks good!")
        sys.exit(exit_code)

    def _install_lint_deps(self) -> None:
        """Install linting dependencies"""
        os.chdir(host_root_dir)
        
        print("Install Lint Dependencies for Python")
        holohub_cli_util.run_command([sys.executable, '-m', 'pip', 'install', '-r',
                    str(host_root_dir / 'utilities/requirements.lint.txt')])
        holohub_cli_util.run_command(['apt', 'install', '--no-install-recommends', '-y',
                    'clang-format=1:14.0*'])

    def handle_setup(self, args: argparse.Namespace) -> None:
        """Handle setup command"""
        # Install system dependencies
        holohub_cli_util.run_command(['sudo', 'apt-get', 'update'], dry_run=args.dryrun)
        holohub_cli_util.run_command(['sudo', 'apt-get', 'install', '-y',
            'build-essential',
            'cmake',
            'git',
            'python3-dev',
            'python3-pip',
            'ninja-build',
            'pkg-config',
            'libglib2.0-dev',
            'clang-format',
            'clang-tidy',
            'cppcheck'
        ], dry_run=args.dryrun)

        # Install Python dependencies
        holohub_cli_util.run_command([sys.executable, '-m', 'pip', 'install', '--upgrade', 'pip'], dry_run=args.dryrun)
        holohub_cli_util.run_command([sys.executable, '-m', 'pip', 'install',
            'cmake-format',
            'cpplint',
            'pytest',
            'pytest-cov',
            'pytest-timeout',
            'black',
            'isort',
            'ruff',
            'codespell'
        ], dry_run=args.dryrun)

        # Create build directory
        self.build_dir.mkdir(parents=True, exist_ok=True)

    def handle_install(self, args: argparse.Namespace) -> None:
        """Handle install command"""
        if args.local:
            app_source = get_app_source_root_dir(args.project, host_root_dir)
            language = args.language or self.get_app_default_language(args.project)
            
            if not language:
                holohub_cli_util.fatal("Could not determine project language. Please specify with --language")
                
            app_source = get_app_source_lang_dir(args.project, language, host_root_dir)
            build_type = self.get_buildtype_str(args.build_type)
            
            # Local install
            build_dir = self.build_dir / args.project
            build_dir.mkdir(parents=True, exist_ok=True)
            
            if language == 'cpp':
                # Build and install C++ project
                holohub_cli_util.run_command([
                    'cmake', '-B', str(build_dir),
                    '-S', str(app_source),
                    f'-DCMAKE_BUILD_TYPE={build_type}',
                    f'-DCMAKE_PREFIX_PATH={self.holoscan_sdk_install}',
                    '-DCMAKE_INSTALL_PREFIX=/usr/local'
                ], dry_run=args.dryrun)
                holohub_cli_util.run_command(['cmake', '--build', str(build_dir), '--config', build_type],
                          dry_run=args.dryrun)
                holohub_cli_util.run_command(['sudo', 'cmake', '--install', str(build_dir)],
                          dry_run=args.dryrun)
            else:
                # For Python projects, install with pip
                if (app_source / "setup.py").exists():
                    holohub_cli_util.run_command([sys.executable, '-m', 'pip', 'install', str(app_source)],
                              dry_run=args.dryrun)
        else:
            # Install in container
            self.container.do_dry_run = args.dryrun
            self.container.build(project=args.project, verbose=args.verbose)
            self.container.launch(
                docker_opts="--entrypoint=bash",
                extra_args=['-c', f'holohub install {args.project} --language {language} --local'],
                verbose=args.verbose
            )

    def handle_clear_cache(self, args: argparse.Namespace) -> None:
        """Handle clear-cache command"""
        if args.dryrun:
            print("Would clear cache folders:")
            for pattern in ['build', 'build-*', 'install']:
                for path in host_root_dir.glob(pattern):
                    if path.is_dir():
                        print(f"  Would remove: {path}")
        else:
            print("Clearing cache...")
            for pattern in ['build', 'build-*', 'install']:
                for path in host_root_dir.glob(pattern):
                    if path.is_dir():
                        shutil.rmtree(path)

    def run(self) -> None:
        """Main entry point for the CLI"""
        args = self.parser.parse_args()
        if hasattr(args, 'func'):
            args.func(args)
        else:
            self.parser.print_help()
            sys.exit(1)

def main():
    cli = HoloHubCLI()
    cli.run()

if __name__ == '__main__':
    main()
