name: Update HoloHub README Statistics

on: [push, pull_request]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Update README
        run: |
          python ./utilities/gather_metadata.py --output aggregate_metadata.json
          app_count=$(cat aggregate_metadata.json | grep "\"source_folder\": \"applications\"" | wc -l)
          sed -i -E "s/Applications-([0-9]+)/Applications-$app_count/" README.md
          ops_count=$(cat aggregate_metadata.json | grep "\"source_folder\": \"operators\"" | wc -l)
          sed -i -E "s/Operators-([0-9]+)/Operators-$ops_count/" README.md
          tutorial_count=$(cat aggregate_metadata.json | grep "\"source_folder\": \"tutorials\"" | wc -l)
          sed -i -E "s/Tutorials-([0-9]+)/Tutorials-$tutorial_count/" README.md
          git diff HEAD -- README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.5
        with:
          add-paths: 'README.md'
          commit-message: '[auto] Update README Project Statistics'
          signoff: true
          branch: readme-auto-update/patch
          title: Update README Project Statistics
          body: 'Automated update to reflect HoloHub project counts in the HoloHub README file.'
          reviewers: tbirdso
